### PR TITLE
4.30

### PR DESCRIPTION
**Pull request by mark0n**
Upgrade to latest stable version which among other things fixes some memory leaks. Please don't forget to push the corresponding pristine-tar and upstream branches as well as the new tag.

### CODE REVIEW

**Comment by mark0n** [comment]
@mdavidsaver, can we please get this merged? The next Asyn release is already waiting to be released...

**Comment by ralphlange** [comment]
Asyn 4.31 has been released today, actually.
What about skipping 4.30?

**Comment by mark0n** [comment]
@ralphlange, we have already deployed 4.30 to production so I would appreciate to see this as another step in the history (just for sanity). Maybe others want to use 4.30 as well? I guess it doesn't hurt to have both 4.30 and 4.31. I'll open another PR for 4.31 later today.

**Comment by mark0n** [comment]
@mdavidsaver is there a chance we can get this merged?

**Pull request merged**
